services:
  postgres:
    image: postgres:16-alpine
    container_name: motil_db
    restart: unless-stopped
    environment:
      POSTGRES_USER:     motil_user
      POSTGRES_PASSWORD: motil_pass
      POSTGRES_DB:       motil_db
    ports:
      - "5432:5432"
    volumes:
      - motil_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U motil_user -d motil_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  motil_pgdata:
